# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Jibjib' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '9.0'
  use_frameworks!
  pod 'Alamofire', '~> 3.4'
  pod 'KMPlaceholderTextView', '~> 1.2.0' 

  # Pods for Jibjib

  target 'JibjibTests' do
    inherit! :search_paths

    # Pods for testing
  end

  target 'JibjibUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
